name: Update Helm Index

on:
  push:
    branches: [gh-pages]
    paths:
      - '*.tgz'
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.CENTRAL_PAT }}

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'  # Use latest stable version

      - name: Debug filesystem
        run: |
          pwd
          ls -lah
          more index.yaml || echo "No existing index.yaml found"

      - name: Index charts
        run: |
          helm repo index . --url https://schnabel45.github.io/helm-charts/

      - name: Debug filesystem
        run: |
          pwd
          ls -lah
          more index.yaml || echo "No existing index.yaml found"

      - name: Commit and Push Updated Index
        run: |
          git add index.yaml
          git commit -m "chore: update index.yaml" || echo "No index change"
          git push